### ISSUE TITLE
Translate for English

### ISSUE THREAD

**Issue by code4craft** [webmagic-io/docs#2]
Translate the Chinese document into English. The articles are in directory "en/posts", and the outline is in "en/SUMMARY.md".

Welcome for participation of below:
1. Find and correct the mistake of English——both grammar of spell.
2. Help to translate an article.

If you want to translate an article, please reply on this issue and give me which part you will translate.

**Comment by alex4ip** [comment]
Dear code4craft
I translated into English from  Chinese.
I plan to be translated into Ukrainian and correct inaccuracies of his translation in English

**Comment by code4craft** [comment]
@alex4ip Thank you so much! Can you send a pull request to me?
